import { parseMarkdown } from "./parseMarkdown";

// Eagerly import all .md files as raw text at build time
const mdModules = import.meta.glob("/data/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
});

// index.json is generated by parse.py
import indexData from "/data/index.json";

/**
 * Load and parse all monthly data.
 * Returns { months: { "2026-01": { title, metrics }, ... }, index }.
 */
export function loadAllData() {
  const months = {};

  for (const [path, rawContent] of Object.entries(mdModules)) {
    const monthMatch = path.match(/(\d{4}-\d{2})\.md$/);
    if (!monthMatch) continue;

    const month = monthMatch[1];
    try {
      months[month] = parseMarkdown(rawContent);
    } catch (e) {
      console.warn(`Failed to parse ${path}:`, e);
    }
  }

  return { months, index: indexData };
}

/**
 * Build a flat list of selectable teams from index.teams.
 * Returns [{ key, label, level }].
 */
export function getTeamList(index) {
  const mapping = index?.teams;
  if (!mapping) return [];

  const list = [];
  const { boss, leaders } = mapping;

  if (boss) {
    list.push({ key: boss, label: `${boss}（大团队）`, level: "boss" });
  }

  if (leaders) {
    for (const subTeams of Object.values(leaders)) {
      for (const [subTeam, smallTeams] of Object.entries(subTeams)) {
        list.push({ key: subTeam, label: subTeam, level: "sub" });
        for (const st of smallTeams) {
          list.push({ key: st, label: st, level: "small" });
        }
      }
    }
  }

  return list;
}

/**
 * Build column grouping info for MonthlyTable's three-level headers.
 * Returns { groups: [{ leader, subGroups: [{ subTeam, columns }] }], boss }
 * or null if mapping is unavailable.
 */
export function buildColumnGroups(index) {
  const mapping = index?.teams;
  if (!mapping || !mapping.leaders) return null;

  const { boss, leaders } = mapping;
  const groups = [];
  const aggregateColumns = []; // column names that are subteam/boss aggregates
  const seen = new Set();

  for (const [leader, subTeams] of Object.entries(leaders)) {
    const subGroups = [];
    for (const [subTeam, smallTeams] of Object.entries(subTeams)) {
      const cols = [];
      // Small teams
      for (const st of smallTeams) {
        if (!seen.has(st)) seen.add(st);
        cols.push(st);
      }
      // Subteam column: dedup if name collides (same logic as parse.py)
      let subName = subTeam;
      let suffix = 2;
      while (seen.has(subName)) {
        subName = `${subTeam}(${suffix})`;
        suffix++;
      }
      seen.add(subName);
      cols.push(subName);
      aggregateColumns.push(subName); // last column = aggregate
      subGroups.push({ subTeam, columns: cols });
    }
    groups.push({ leader, subGroups });
  }

  aggregateColumns.push(boss);

  return { groups, boss, aggregateColumns };
}
