import { parseMarkdown } from "./parseMarkdown";

// Eagerly import all .md files as raw text at build time
const mdModules = import.meta.glob("/data/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
});

// index.json is generated by parse.py
import indexData from "/data/index.json";

// trend.json is generated by parse.py when trend_metrics are configured.
import trendData from "/data/trend.json";

/**
 * Load and parse all monthly data.
 * Returns { months: { "2026-01": { title, metrics }, ... }, index }.
 */
export function loadAllData() {
  const months = {};

  for (const [path, rawContent] of Object.entries(mdModules)) {
    const monthMatch = path.match(/(\d{4}-\d{2})\.md$/);
    if (!monthMatch) continue;

    const month = monthMatch[1];
    try {
      months[month] = parseMarkdown(rawContent);
    } catch (e) {
      console.warn(`Failed to parse ${path}:`, e);
    }
  }

  return { months, index: indexData, trendData };
}


/**
 * Build column grouping info for MonthlyTable's three-level headers.
 * Returns { groups: [{ leader, subGroups: [{ subTeam, columns }] }], boss }
 * or null if mapping is unavailable.
 */
export function buildColumnGroups(index, headers = []) {
  const mapping = index?.teams;
  if (!mapping || !mapping.leaders) return null;

  const { boss, leaders, aggregate_column_names: aggregateNames = {} } = mapping;
  const groups = [];
  const aggregateColumns = []; // column names that are subteam/boss aggregates
  const seen = new Set();
  const activeVirtualAggregates = (mapping.virtual_aggregates || []).filter(
    (aggregate) => headers.includes(aggregate.name),
  );

  for (const [leader, subTeams] of Object.entries(leaders)) {
    const subGroups = [];
    for (const [subTeam, smallTeams] of Object.entries(subTeams)) {
      const cols = [];
      // Small teams
      for (const st of smallTeams) {
        if (!seen.has(st)) seen.add(st);
        cols.push(st);
        for (const aggregate of activeVirtualAggregates) {
          if (aggregate.sub_team === subTeam && aggregate.after === st) {
            cols.push(aggregate.name);
            aggregateColumns.push(aggregate.name);
          }
        }
      }
      // Subteam column: dedup if name collides (same logic as parse.py)
      let subName = seen.has(subTeam)
        ? aggregateNames[subTeam] || subTeam
        : subTeam;
      let suffix = 2;
      while (seen.has(subName)) {
        subName = `${subTeam}(${suffix})`;
        suffix++;
      }
      seen.add(subName);
      cols.push(subName);
      aggregateColumns.push(subName); // last column = aggregate
      subGroups.push({ subTeam, columns: cols });
    }
    groups.push({ leader, subGroups });
  }

  aggregateColumns.push(boss);

  return { groups, boss, aggregateColumns };
}
