/**
 * Parse Markdown (generated by parse.py) into structured JS objects.
 *
 * Expected format:
 *   # 2026年1月 财务数据
 *
 *   ## 回款目标（万元）
 *   | 小团队A | 小团队B | 子团队1 | ... |
 *   |---|---|---|---|
 *   |  100 |  200 |  300 | ... |
 *
 *   ## 现金支出（万元）
 *   | ... |
 */
export function parseMarkdown(mdContent) {
  const metrics = {};

  // Split on "## " to isolate each metric section
  const parts = mdContent.split(/^## /m);

  // The first part (before any "## ") contains the H1 title
  const titleMatch = parts[0].match(/^# (.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : "";

  // Process each metric section
  for (let i = 1; i < parts.length; i++) {
    const section = parts[i];
    const lines = section.split("\n");

    const metricName = lines[0].trim();
    if (!metricName) continue;

    // Locate the markdown table: header row, separator row, data row
    const headerIdx = lines.findIndex((l) => l.startsWith("|"));
    if (headerIdx === -1) continue;

    const headerLine = lines[headerIdx];
    const headers = headerLine
      .split("|")
      .map((h) => h.trim())
      .filter(Boolean);

    // Data row is 2 lines after header (skipping separator)
    const dataLine = lines[headerIdx + 2];
    if (!dataLine || !dataLine.startsWith("|")) continue;

    const rawValues = dataLine
      .split("|")
      .map((v) => v.trim())
      .filter(Boolean);

    const values = rawValues.map((v) => {
      if (v === "-") return null;
      const n = parseFloat(v);
      return isNaN(n) ? v : n;
    });

    metrics[metricName] = { headers, values };
  }

  return { title, metrics };
}
